import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Josefin_Sans, Outfit, Roboto } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ['latin'],
})
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ['latin'],
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ['latin'],
})

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doni Arifin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${outfit.variable} ${josefinSans.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
